baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'ms-home'
theme = 'coming-soon'

[params]
    title = " " 
    description = ""
    favicon = ""
    message = "COMING SOON!" 
    release = "November 11, 2024" 
    background = "" 

socialIcons = [
    {name = "email", url = "mike.shemanskiy@gmail.com"},      
    # {name = "twitter", url = "https://twitter.com/"},    
    # {name = "facebook", url = "https://facebook.com/"},    
    # {name = "github", url = "https://github.com/"},    
    # {name = "instagram", url = "https://instagram.com/"},    
    # {name = "tiktok", url = "https://tiktok.com/"},    
] 
